[package]
name = "sad"
version = "0.1.0"
authors = ["Fly me to the moon <git@bigly.dog>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1"
clap = "3.0.0-beta.1"
tokio = { version = "0.2", features = ["full"] }
regex = "1"
aho-corasick = "0.7"
difference = "2"
