[package]
name = "sad"
version = "0.1.0"
authors = ["Fly me to the moon <git@bigly.dog>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1"
futures = "0.3"
async-std = { version = "1", features = ["unstable"] }
clap = { version = "3.0.0-beta.1", features = ["wrap_help"] }
regex = "1"
aho-corasick = "0.7"
difference = "2"
