---

name: CI

on:
  push:
    paths:
      - "Cargo.toml"
      - "src/**"
      - "tests/**"
      - ".github/**"
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: cargo test

      - name: Build
        run: cargo build --release

      - name: Package Artifacts
        run: |-
          chmod +x target/release/sad
          zip -j artifacts/sad-macos.zip target/release/sad

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sad-macos
          path: artifacts/sad-macos.zip

  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./ci/docker.py linux

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sad-linux
          path: artifacts/sad-linux.zip

  build_debs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./ci/docker.py deb

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sad-deb
          path: artifacts/sad.deb

