name: CI

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: target/release/sad
