---

name: CI

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/**"
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: |-
          rustup component add clippy
          # cargo clippy -- -D clippy::all

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

      - name: Package Artifacts
        run: |-
          chmod +x target/debug/sad
          zip -j artifacts/${{ matrix.os }} target/debug/sad

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: artifacts/${{ matrix.os }}.zip

