name: Release

on:
  push:
    # tags:
    #   - "*"

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: cargo test --verbose

      - name: Build
        run: cargo build --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: target/release/sad

  release:
    needs:
      - build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: artifacts/${{ matrix.os }}

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Pip Packages
        run: pip install toml

      - name: Set ENV
        id: set_env
        run: |-
          ./scripts/ci.py --release

      - name: Create Release
        id: new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_env.outputs.TAG_NAME }}
          release_name: ${{ steps.set_env.outputs.RELEASE_NAME }}
          draft: false
          prerelease: false

      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.new_release.outputs.upload_url }}
          asset_content_type: application/zip
          asset_path: artifacts/${{ matrix.os }}/sad
          asset_name: ${{ matrix.os }}
