---

name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build_zips:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: cargo test --verbose

      - name: Build
        run: cargo build --release

      - name: Package Artifacts
        run: |-
          chmod +x target/release/sad
          zip -j artifacts/${{ matrix.os }} target/release/sad

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: artifacts/${{ matrix.os }}.zip

  build_debs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deb Builder
        run: cargo install cargo-deb

      - name: Test
        run: cargo test --verbose

      - name: Build
        run: cargo deb --output target/debian/debian.deb

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debian_deb
          path: target/debian/debian.deb

  release:
    needs:
      - build_zips
      - build_debs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifacts macos
        uses: actions/download-artifact@v2
        with:
          name: macos-latest
          path: artifacts

      - name: Download Artifacts ubuntu
        uses: actions/download-artifact@v2
        with:
          name: ubuntu-latest
          path: artifacts

      - name: Download Artifacts debian deb
        uses: actions/download-artifact@v2
        with:
          name: debian_deb
          path: artifacts

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Pip Packages
        run: |-
          ./ci/pip.sh

      - name: Set ENV
        id: set_env
        run: |-
          ./ci/ci.py --release

      - name: Create Release
        id: new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ fromJSON(steps.set_env.outputs.RELEASE_INFO).tag_name }}
          release_name: ${{ fromJSON(steps.set_env.outputs.RELEASE_INFO).release_name }}
          body: ${{ fromJSON(steps.set_env.outputs.RELEASE_INFO).release_notes }}
          draft: false
          prerelease: false

      - name: Upload Asset - Macos
        id: asset_macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.new_release.outputs.upload_url }}
          asset_content_type: application/zip
          asset_path: artifacts/macos-latest.zip
          asset_name: x86_64-apple-darwin.zip

      - name: Upload Asset - Ubuntu
        id: asset_ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.new_release.outputs.upload_url }}
          asset_content_type: application/zip
          asset_path: artifacts/ubuntu-latest.zip
          asset_name: x86_64-unknown-linux-gnu.zip

      - name: Upload Asset - Debian deb
        id: asset_debian
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.new_release.outputs.upload_url }}
          asset_content_type: application/vnd.debian.binary-package
          asset_path: artifacts/debian.deb
          asset_name: x86_64-unknown-linux-gnu.deb

      - name: Homebrew
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: >-
          ./ci/release.py
          --brew-artifact=macos-latest.zip
          --brew-uri=${{ steps.asset_macos.outputs.browser_download_url }}

      - name: Snapcraft
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: >-
          ./ci/release.py
          --snapcraft

