name: Testing

on:
  push:
    # tags:
    #   - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Pip Packages
        run: pip install toml pyyaml jinja2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Git
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |-
          ./ci/release.py
          cd packages
          echo 555 >> testing.txt
          git add -A
          git commit -m "testing"
          git push
