name: Testing

on:
  push:
    # tags:
    #   - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Git
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |-
          ./ci/ci.py
          cd packages
          echo 555 >> testing.txt
          git add -A
          git commit -m "testing"
          git push "https://ms-jpq:$CI_TOKEN@github.com/ms-jpq/homebrew-sad.git" master
